datasets_path: C:\Datasets
random_seed: 230

batch_size: 32
train_batches: 1000
val_batches: 2
test_batches: 2
max_epochs: 100

log_every_n_steps: 10

accelerator: gpu
devices: 1
strategy: dp

num_workers: 1
persistent_workers: True