datasets_path: C:\Datasets
random_seed: 230

learning_rate: 0.001

batch_size: 4
train_batches: 10
val_batches: 2
test_batches: 2
max_epochs: 10
shuffle: True
drop_last: True

log_every_n_steps: 10
checkpoint_dirpath: C:\SpeechDARE\checkpoints

accelerator: gpu
devices: 1
strategy: dp

num_workers: 8
pin_memory: True
persistent_workers: True
