datasets_path: ./Datasets
random_seed: 230

stft_format: realimag # realimag or magphase
stft_format_sp: magphase
rir_duration: 32767
nfft: 16383
nhop: 2048
nfrms: 16
min_early_reverb: 0.000 # 0.007 is actual...minimum permitted early reverb time for considered RIRs(seconds). The early reverb is taken to be the time where the RIR is at its maximum value.
echo_encode: True
prealign_rir: False
norm_audio : True

data_in_ram: False

Encoding: # echo encoding params
  delays: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100] 
  amplitude: 0.4
  win_size: 2048
  kernel: "bp"
  decoding: "cepstrum" # options: "autocepstrum", "cepstrum"
  cutoff_freq: 1000

Model:
  model_name: EchoSpeechDAREUnet
  learning_rate: 0.0001
  nfft: 8192
  nfrms: 16
  use_transformer: True
  use_speechbranch: True
  alph: 1

DataLoader:
  batch_size: 16
  num_workers: 16
  persistent_workers: True
  shuffle: True
  drop_last: True
  pin_memory: True

ModelCheckpoint:
  monitor: val_loss
  dirpath: cepstrum_checkpoints

LearningRateMonitor:
  logging_interval: epoch

DDPStrategy:
  process_group_backend: gloo
  find_unused_parameters: False

AdvancedProfiler:
  dirpath: null
  filename: advanced_profiler.txt
  line_count_restriction: 1.0

Trainer:
  limit_train_batches: 1000 #2220
  limit_val_batches: 3
  limit_test_batches: 111
  max_epochs: 100
  # reload_dataloaders_every_n_epochs: 1
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  log_every_n_steps: 100
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: [1]

# RichProgressBar:
#   refresh_rate: 100
#   leave: True

# RichProgressBarTheme:
#   description: green_yellow
#   progress_bar: green1
#   progress_bar_finished: green1
#   progress_bar_pulse: '#6206E0'
#   batch_progress: green_yellow
#   time: grey82
#   processing_speed: grey82
#   metrics: grey82
