datasets_path: 'C:\Datasets'
random_seed: 230

data_in_ram: False

stft_format: realimag # realimag or magphase
rir_duration: 32767
nfft: 32767
nhop: 4096
nfrms: 16

Model:
  model_name: SpeechDAREUnet_v2
  learning_rate: 0.001

DataLoader:
  batch_size: 96
  num_workers: 2
  persistent_workers: True
  shuffle: True
  drop_last: True
  pin_memory: True

ModelCheckpoint:
  monitor: val_loss
  dirpath: checkpoints

LearningRateMonitor:
  logging_interval: epoch

DataParallelStrategy:
  # process_group_backend: gloo
  # find_unused_parameters: False
  accelerator: gpu

AdvancedProfiler:
  dirpath: null
  filename: advanced_profiler.txt
  line_count_restriction: 1.0

Trainer:
  limit_train_batches: 5715
  limit_val_batches: 28
  limit_test_batches: 286
  max_epochs: 100
  # reload_dataloaders_every_n_epochs: 1
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  log_every_n_steps: 100
  # accelerator: gpu
  devices: 4

RichProgressBarTheme:
  description: green_yellow
  progress_bar: green1
  progress_bar_finished: green1
  progress_bar_pulse: '#6206E0'
  batch_progress: green_yellow
  time: grey82
  processing_speed: grey82
  metrics: grey82
