datasets_path: ./Datasets
random_seed: 230

stft_format: realimag # realimag or magphase
stft_format_sp: magphase # not used for Wavenet
sample_rate: 16000
rir_duration: 32777
nfft: 32767
nhop: 4096
nfrms: 16
min_early_reverb: 0.004 # minimum permitted early reverb time for considered RIRs(seconds). The early reverb is taken to be the time where the RIR is at its maximum value.
echo_encode: True
prealign_rir: False
               
data_in_ram: False


Encoding: # echo encoding params
  delays: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149] 
  amplitude: 0.8
  win_size: 2048
  kernel: "bp"
  decoding: "autocepstrum" # options: "autocepstrum", "cepstrum"
  cutoff_freq: 1000


Model:
  model_name: Waveunet
  learning_rate: 0.00001 #0.000001

DataLoader:
  batch_size: 8
  shuffle: True
  drop_last: True
  num_workers: 12
  pin_memory: True
  persistent_workers: True

ModelCheckpoint:
  monitor: val_loss
  dirpath: checkpoints

LearningRateMonitor:
  logging_interval: epoch

DDPStrategy:
  process_group_backend: gloo
  find_unused_parameters: False

AdvancedProfiler:
  dirpath: null
  filename: advanced_profiler.txt
  line_count_restriction: 1.0

Trainer:
  limit_train_batches: 10000 #20000
  limit_val_batches: 100
  limit_test_batches: 100
  max_epochs: 100
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1
  profiler: null

RichProgressBarTheme:
  description: green_yellow
  progress_bar: green1
  progress_bar_finished: green1
  progress_bar_pulse: '#6206E0'
  batch_progress: green_yellow
  time: grey82
  processing_speed: grey82
  metrics: grey82

WaveUnet:
  channels: 1
  kernel_size_down: 15
  kernel_size_up: 5
  levels: 12
  features: 24
  feature_growth: add
  output_size: 2.0
  sr: 16000
  conv_type: bn
  res: fixed